### PR TITLE
registry: move cmake, pkg-config, and hooks to native-build-inputs

### PR DESCRIPTION
**Pull request by figsoda**

### CODE REVIEW

**Comment by figsoda** [comment]
cc @cole-h

**Review by cole-h — APPROVED** [review]

**Comment by figsoda** [comment]
Any chance for this to get deployed to https://registry.riff.determinate.systems/riff-registry.json? or does it only happen when new versions are released

**Comment by cole-h** [comment]
Should be done now.

**Comment by figsoda** [comment]
thanks!

**Pull request merged**
